### ISSUE TITLE
Errors during indexing-process

### ISSUE THREAD

**Issue by reneglauser** [nextcloud/files_fulltextsearch#1]
If I activate this app, I get a lot of the following errors during the indexing-process:

. Indexing: servername/foldername/problematic-file

[Elasticsearch\Common\Exceptions\BadRequest400Exception]
  {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"pipeline with id [attachment] does not exist"}],"type":"illegal_argument_exception","reason":"pipeline with id [attachment] does not exist"}
  ,"status":400}

If this error occures, the indexing-process is stopped immediately. After the problematic-file has been deleted, the process does not stop until the next problematic-file is going to be indexed....

**Comment by daita** [comment]
Try this: https://help.nextcloud.com/t/fullnextsearch-is-now-beta/25220/4?u=cult

**Comment by reneglauser** [comment]
thanks for this. I just installed the plugin but I still get the same error. But I also get the error on plaintext content such as txt files.....

**Comment by daita** [comment]
Even after a restart of the elasticsearch servlet and the ./occ fullnextsearch:reset ?

**Comment by reneglauser** [comment]
thanks.....after a complet reboot of the server and fullnextsearch:reset it seems to work now as expected. I now have to wait until the process is finished.....

**Comment by reneglauser** [comment]
Is there a possibility to limit the indexing-process of files to certain file-types such as docx, etc ...? No a lot of unwanted files seems to be indexed too and I got this error at a specific file:

[Elasticsearch\Common\Exceptions\BadRequest400Exception]
  {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse [attachment.date]"}],"type":"mapper_parsing_exception","reason"
  :"failed to parse [attachment.date]","caused_by":{"type":"illegal_argument_exception","reason":"Invalid format: \"10091-02-18T08:28:45Z\" is malform
  ed at \"1-02-18T08:28:45Z\""}},"status":400}

**Comment by daita** [comment]
Yes, there will be more settings/options in a future version. Can you provide more information regarding this file (format, size, ...) ? Is the index stuck on that file ?

**Comment by Japhys** [comment]
I am not sure what I am doing wrong

Clean NC 13 beta
Clean Elastic search
Clean FullTextSearch

But when i run index command i also get:

[Elasticsearch\Common\Exceptions\BadRequest400Exception]
  {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"pipeline with id [attachment] does not exist"}],"type":"illegal_argument_e
  xception","reason":"pipeline with id [attachment] does not exist"},"status":400}


I did a reset and a restart.

**Comment by daita** [comment]
Yes, next release will first check that the plugin is installed.
