### ISSUE TITLE
Support Nextcloud 23

### ISSUE THREAD

**Issue by dwt** [nextcloud/files_fulltextsearch#144]
I see the update for nextcloud 23 is shown as available, but the fulltextsearch plugin is still missing compatibility. Is this something that you guys are already working on? Is there anything the community can do to help?

**Comment by Judhianto** [comment]
please help. 
i didn't realize when upgrade to nextcloud 23, and now i can not search for document content

**Comment by ornago** [comment]
Sigh, didn't hit update yet.
https://apps.nextcloud.com/apps/files_fulltextsearch_tesseract/releases?platform=23
Tesseract seems to be compatible, hope the rest follows soon?

**Comment by dwt** [comment]
I am now using this successfully with nextcloud 23 successfully. Closing.
