### ISSUE TITLE
[0.7.2] Warnings in ConfigService.php

### ISSUE THREAD

**Issue by patschi** [nextcloud/files_fulltextsearch#15]
When performing a manual index of my files using
```
sudo -u www-data /usr/bin/php /var/www/nextcloud/occ fulltextsearch:index
```
a couple of PHP warnings are shown in the nextcloud log. These are follows:

Level | App | Message | Time
-- | -- | -- | --
Error | PHP | Invalid argument supplied for foreach() at /var/www/nextcloud/apps/files_fulltextsearch/lib/Service/ConfigService.php#260 | 2018-05-31T13:12:07+0200
Error | PHP | array_keys() expects parameter 1 to be array, null given at /var/www/nextcloud/apps/files_fulltextsearch/lib/Service/ConfigService.php#259 | 2018-05-31T13:12:07+0200

They are caused in the function `compareIndexOptions()`, see [lib/Service/ConfigService.php#L252](https://github.com/nextcloud/files_fulltextsearch/blob/master/lib/Service/ConfigService.php#L252).

I would suggest adding/adapting following in the mentioned function:
```php
if (!is_array($options) || count($options) === 0) {
	return false;
}
```

As I'm not fimiliar with the app structure enough I rather opened a ticket than a pull request, as I'm not aware of possible side effects that might cause or if they might be better solutions.

**Comment by daita** [comment]
fixed in 0.8.0
