### ISSUE TITLE
Search "Within current directory" always no results

### ISSUE THREAD

**Issue by mirsch** [nextcloud/files_fulltextsearch#16]
If I check "Within current directory" I get 0 Results. If I uncheck the box, the files are found. This happens on all folders/files

Nextcloud 13.0.5
Full text search - Elasticsearch Platform (BETA)	0.8.0
Full text search - Files (BETA) 0.8.2
Full text search (BETA)	0.8.1

**Comment by daita** [comment]
fixed next release
