### ISSUE TITLE
AFTER UPGRADING TO NC24 [ TypeError: Argument 2 passed to OCA\Files_FullTextSearch\Service\FilesService::getInt() must be of the type array, bool given, called in /var/www/nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php on line 500  ]

### ISSUE THREAD

**Issue by ralphy-cmd** [nextcloud/files_fulltextsearch#168]
Hi together,

I have this issue after running occ fulltextsearch:index after upgrading nextcloud from version 23 to 24:

An unhandled exception has been thrown:
TypeError: Argument 2 passed to OCA\Files_FullTextSearch\Service\FilesService::getInt() must be of the type array, bool given, called in /var/www/nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php on line 500 and defined in /var/www/nextcloud/apps/files_fulltextsearch_tesseract/vendor/artificial-owl/my-small-php-tools/lib/Traits/TArrayTools.php:102
Stack trace:
#0 /var/www/nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php(500): OCA\Files_FullTextSearch\Service\FilesService->getInt()
#1 /var/www/nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php(421): OCA\Files_FullTextSearch\Service\FilesService->generateFilesDocumentFromFile()
#2 /var/www/nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php(318): OCA\Files_FullTextSearch\Service\FilesService->generateFilesDocumentFromParent()
#3 /var/www/nextcloud/apps/files_fulltextsearch/lib/Provider/FilesProvider.php(269): OCA\Files_FullTextSearch\Service\FilesService->getFilesFromUser()
#4 /var/www/nextcloud/apps/fulltextsearch/lib/Service/IndexService.php(183): OCA\Files_FullTextSearch\Provider\FilesProvider->generateIndexableDocuments()
#5 /var/www/nextcloud/apps/fulltextsearch/lib/Command/Index.php(416): OCA\FullTextSearch\Service\IndexService->indexProviderContentFromUser()
#6 /var/www/nextcloud/apps/fulltextsearch/lib/Command/Index.php(279): OCA\FullTextSearch\Command\Index->indexProvider()
#7 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\FullTextSearch\Command\Index->execute()
#8 /var/www/nextcloud/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run()
#9 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run()
#10 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#11 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#12 /var/www/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#13 /var/www/nextcloud/console.php(99): OC\Console\Application->run()
#14 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#15 {main}root@cloud:/home/nc# sudo -u www-data php /var/www/nextcloud/occ fulltextsearch:index

occ fulltextsearch:live works but hangs up (no progress, even after waiting for hours). Before the update everything worked fine. I don't have this type of error on the other 4 nextcloud instances I updated to version 24. It seems a bit strange, because the server where the error appears is the newest instace (was installed with nextcloud v23).

If I deactivate the "FULLTEXTSEARCH - FILES" app, the error disappears. I guess it's a bug in the app.

Thanks in advance for any help.

Best regards,
ralphy cmd

**Comment by XueSheng-GIT** [comment]
Same error msg as https://github.com/nextcloud/fulltextsearch/issues/703. 
https://github.com/nextcloud/files_fulltextsearch/pull/172 did fix it for me.

**Comment by joshtrichards** [comment]
Fixed in #172
