### ISSUE TITLE
unhandled exception in FilesService

### ISSUE THREAD

**Issue by asaage** [nextcloud/files_fulltextsearch#169]
```
An unhandled exception has been thrown:
Error: Call to a member function getUID() on null in 
/var/www//nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php:449
```
I did the NC 24 update.

- ```occ fulltextsearch:check``` and ```occ fulltextsearch:test``` all OK.
- ```occ fulltextsearch:migration:24``` done.
- I did fulltextsearch:stop and fulltextsearch:reset to then reindex all files.
- ```occ fulltextsearch:index```  results in the mentioned error.

If i run ```occ fulltextsearch:index```  again it tells me "In RunningService.php line 86: Index is already running"

The frontend doesn't get me any searchresults though.

**Comment by lockdlock** [comment]
I have the same problem.
I have addressed it by comment out the relevant line.
I do not know if this is the right thing to do.

`nano +449 /var/www//nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php`
line 449 is comment out

**Comment by asaage** [comment]
> `nano +449 /var/www//nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php` line 449 is comment out

Probably presents the search-results for files that you are not supposed to see.
I don't think that's the way to go.

**Comment by asaage** [comment]
> Same error msg as [nextcloud/fulltextsearch#697](https://github.com/nextcloud/fulltextsearch/issues/697). #170 did fix it for me.

Thanks for the hint - i'm not going to patch this manually though but wait for the next release.
