### ISSUE TITLE
NC14.0.1 & files_fulltextsearch 1.0.0: "App is not compliant"

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/files_fulltextsearch#20]
`occ app:check-code files_fulltextsearch`

```
Analysing /var/www/html/apps/files_fulltextsearch/lib/Service/ExternalFilesService.php
 1 errors
    line   47: OCP\App - deprecated class must not be imported with a use statement
Invalid appinfo.xml file found: Element 'namespace': This element is not expected. Expected is one of ( documentation, category ).

App is not compliant
```

What does this mean?
Thank you!

**Comment by daita** [comment]
the fulltextsearch search needs to be added to the info.xsd

**Comment by teadur** [comment]
I tried to upgrade my NC to 14.X and files_fulltextsearch  1.1.1 reported:

this app cannot be installed because the following dependencies are not fulfilled:
        Server version 13 or lower is required.
Extension to the Full text search app to index your users' files.

**Comment by acsfer** [comment]
The app code checker doesn't check anything anymore and this command will be removed in Nextcloud 23.
