### ISSUE TITLE
Nextcloud 25 support

### ISSUE THREAD

**Issue by jacotec** [nextcloud/files_fulltextsearch#204]
Nextcloud 25 is out a while and the fulltextsearch apps are currently blocking my update ...

**Comment by arnowelzel** [comment]
You can manually enable the apps and activate them - theys work fine in NC 25 as well.

However it would be nice to update the compatibility information anyway.

**Comment by p-bo** [comment]
Seems to be fixed now: https://apps.nextcloud.com/apps/files_fulltextsearch/releases?platform=25#25

**Comment by joshtrichards** [comment]
Fixed in #206
