### ISSUE TITLE
Compability for NC 26

### ISSUE THREAD

**Issue by RunnerLexico** [nextcloud/files_fulltextsearch#214]
Nextcloud 26 is out and the fulltextsearch apps are not compatible yet.

Does it work with Nextcloud 26?

Thanks and regards

**Comment by joshlukas** [comment]
Not working right now. At least with 26.0.0. Haven't tried with 26.0.1, but I think the developer of fulltext search must ensure compatibility with NC 26.

**Comment by joshtrichards** [comment]
Fixed in #216
