### ISSUE TITLE
Not working after update v26

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/files_fulltextsearch#219]
After update to v26 the UI fulltext search disappeared from the search results completely.

`Full text search 26.0.0

- Search Platform:
Elasticsearch 26.0.0 (Selected)
{
    "elastic_host": [
        "http://localhost:9200"
    ],
    "elastic_index": "elasticsearch",
    "fields_limit": "10000",
    "es_ver_below66": "0",
    "analyzer_tokenizer": "standard"
}

- Content Providers:
Files 26.0.0
{
    "files_local": "1",
    "files_external": "2",
    "files_group_folders": "1",
    "files_encrypted": "0",
    "files_federated": "0",
    "files_size": "10",
    "files_pdf": "1",
    "files_office": "1",
    "files_image": "0",
    "files_audio": "0",
    "files_chunk_size": "2",
    "files_fulltextsearch_tesseract": {
        "version": "25.0.0",
        "enabled": "1",
        "psm": "4",
        "lang": "ukr,eng",
        "pdf": "0",
        "pdf_limit": "10"
    }
}`

**Comment by joshtrichards** [comment]
Are you still experiencing this?

**Comment by ostasevych** [comment]
> Are you still experiencing this?

It seems, it is fine now.
