### ISSUE TITLE
Error with Full Text Search on occ fulltextsearch:index

### ISSUE THREAD

**Issue by KaraokeStu** [nextcloud/files_fulltextsearch#22]
### Running:

- Nextcloud 15 Beta 2 via Docker
- Elastic Search (2 node cluster) via Docker

### Plugins Installed:

- Full text search 1.2.0
- Full text search - Elasticsearch Platform 1.2.0
- Full text search - Files 1.2.0

### Problem:

The following error comes up when attempting to "occ fulltextsearch:index":

`An unhandled exception has been thrown:
TypeError: Argument 1 passed to OCA\Files_FullTextSearch\Model\FilesDocument::setOwnerId() must be of the type string                 , boolean given, called in /apps2/files_fulltextsearch/lib/Service/FilesService.php on line 289 and defined in /apps2                 /files_fulltextsearch/lib/Model/FilesDocument.php:69
Stack trace:
#0 /apps2/files_fulltextsearch/lib/Service/FilesService.php(289): OCA\Files_FullTextSearch\Model\FilesDocument->setOw                 nerId(false)
#1 /apps2/files_fulltextsearch/lib/Service/FilesService.php(247): OCA\Files_FullTextSearch\Service\FilesService->gene                 rateFilesDocumentFromFile('admin', Object(OC\Files\Node\Folder))
#2 /apps2/files_fulltextsearch/lib/Service/FilesService.php(188): OCA\Files_FullTextSearch\Service\FilesService->getF                 ilesFromDirectory('admin', Object(OC\Files\Node\Folder))
#3 /apps2/files_fulltextsearch/lib/Provider/FilesProvider.php(228): OCA\Files_FullTextSearch\Service\FilesService->ge                 tFilesFromUser('admin', Object(OCA\FullTextSearch\Model\IndexOptions))
#4 /apps2/fulltextsearch/lib/Service/IndexService.php(179): OCA\Files_FullTextSearch\Provider\FilesProvider->generate                 IndexableDocuments('admin')
#5 /apps2/fulltextsearch/lib/Command/Index.php(407): OCA\FullTextSearch\Service\IndexService->indexProviderContentFro                 mUser(Object(OCA\FullTextSearch_ElasticSearch\Platform\ElasticSearchPlatform), Object(OCA\Files_FullTextSearch\Provid                 er\FilesProvider), 'admin', Object(OCA\FullTextSearch\Model\IndexOptions))
#6 /apps2/fulltextsearch/lib/Command/Index.php(271): OCA\FullTextSearch\Command\Index->indexProvider(Object(OCA\Files                 _FullTextSearch\Provider\FilesProvider), Object(OCA\FullTextSearch\Model\IndexOptions))
#7 /nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\FullTextSearch\Command\Index->execute(Object(Sym                 fony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /nextcloud/core/Command/Base.php(166): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Con                 sole\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /nextcloud/3rdparty/symfony/console/Application.php(946): OC\Core\Command\Base->run(Object(Symfony\Component\Conso                 le\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /nextcloud/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Obj                 ect(OCA\FullTextSearch\Command\Index), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Co                 nsole\Output\ConsoleOutput))
#11 /nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Sym                 fony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Co                 mponent\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /nextcloud/console.php(96): OC\Console\Application->run()
#14 /nextcloud/occ(11): require_once('/nextcloud/cons...')
`

**Comment by amd-64** [comment]
Exactly my situation.

**Comment by d235j** [comment]
I got this error as well.

**Comment by lhurt** [comment]
me too

**Comment by prolibre** [comment]
me too

**Comment by amd-64** [comment]
Resolved in FTS 1.2.1. Can be closed. Thanks

**Comment by prolibre** [comment]
Hello @amd-64 

the last commit (Dec 14, 2018 > 1.2.1) cannot solve the problem (9 small additions and 2 deletions). It's strange that it works for you ???

**Comment by d235j** [comment]
It doesn't seem resolved for me.

**Comment by GammaPi** [comment]
Same problem when both group folders and external storage are checked.

**Comment by acsfer** [comment]
Can you please confirm this still hapens with both latest versions of Nexcloud and `files_fulltextsearch` apps?

**Comment by joshtrichards** [comment]
It's been 2+ years with no follow-up info suggesting this is ongoing so closing. If someone disagrees feel free to provide evidence and version info.
