### ISSUE TITLE
TypeError: Return value of OCA\Files_FullTextSearch\Events\FilesEvents::get() must be of the type string, integer returned

### ISSUE THREAD

**Issue by dae1804** [nextcloud/files_fulltextsearch#23]
NextCloud 14.0.4 on Apache2 + PHP7, with the following apps installed:
* Full text search 1.1.0
* Full text search - Elasticsearch Platform 1.0.2
* Full text search - Files 1.1.1

...produces this error when attempting to share files via the [Thunderbird file-link addon](https://github.com/nextcloud/nextcloud-filelink) (v1.8):

    TypeError: Return value of OCA\Files_FullTextSearch\Events\FilesEvents::get() must be of the type string, integer returned at /var/www/nextcloud/apps/files_fulltextsearch/vendor/daita/my-small-php-tools/lib/Traits/TArrayTools.php#52

...which causes an error to be returned to Thunderbird, causing the file-link operation to fail.  This appears to be because the itemSource key in the `$params` array is an integer, but the `get()` method inherited from the `TArrayTools` trait is expecting this to be a string.  Here's the `var_dump($params)`:

    array(12) {
      ["itemType"]=>
      string(4) "file"
      ["itemSource"]=>
      int(3525727)
      ["shareType"]=>
      int(3)
      [... snip ...]
    }

I'm not familiar enough with the NextCloud or file-link addon codebases to tell if this is an issue with how upstream code is expressing the file-id/`itemSource` (i.e. as an int instead of a string), or if files_fulltextsearch is being overly picky.  In any case, commenting out the body of `FilesEvents::onFileShare()` prevents the error and allows the upload/share from Thunderbird to complete successfully, which suggests that NextCloud-core, at least, is tolerant of this value being expressed as an int.

**Comment by daita** [comment]
can we close this issue ?

**Comment by dae1804** [comment]
I believe so; it works for me with NC 15.0.2 + files_fulltextsearch 1.2.3.  Looks like your changes in eb7a2531 did the trick.

Sorry for not responding sooner -- I didn't realize you had a new release out since I was still back on NC14.
