### ISSUE TITLE
Released 27.0.0 lacks fix from #227 & #231

### ISSUE THREAD

**Issue by DrMurx** [nextcloud/files_fulltextsearch#234]
The tarball currently available as [27.0.0 release](https://github.com/nextcloud-releases/files_fulltextsearch/releases/download/27.0.0/files_fulltextsearch-27.0.0.tar.gz) in the NextCloud App Store doesn't include the fixes in #227 and #231. Can you please release a 27.0.1?

**Comment by kboykov** [comment]
Can you update the backport, please?

**Comment by DrMurx** [comment]
@ArtificialOwl Please?

![PrettyPlease](https://github.com/nextcloud/files_fulltextsearch/assets/1222566/a5f493fd-ed7a-4bea-ab19-3b8dcafdd55c)

**Comment by kboykov** [comment]
Please, do release the hotfix update. This is not serious.

**Comment by DrMurx** [comment]
@ArtificialOwl Any progress here? Can we help somehow to make this release happen?

**Comment by DrMurx** [comment]
I just discovered 27.0.1 released one week ago which includes the fixes #227 and #231, amongst others.

This solved the problem with fulltext search and groupfolders for me (and may solve #233), so I'll proceed and close this issue.
