### ISSUE TITLE
TypeError: Argument 1 passed to OCA\Files_FullTextSearch\Service\SearchService::setDocumentInfo() must be an instance of OCA\Files_FullTextSearch\Model\FilesDocument, instance of OCP\FullTextSearch\Model\IndexDocument given, called in /var/www/html/custom_apps/files_fulltextsearch/lib/Service/SearchService.php on line 217

### ISSUE THREAD

**Issue by Maurice-Mueller** [nextcloud/files_fulltextsearch#25]
Thanks for the awesome plugin!

In Nextcloud 15 I get the following error (Plugin version: 1.2.0):

`TypeError: Argument 1 passed to OCA\Files_FullTextSearch\Service\SearchService::setDocumentInfo() must be an instance of OCA\Files_FullTextSearch\Model\FilesDocument, instance of OCP\FullTextSearch\Model\IndexDocument given, called in /var/www/html/custom_apps/files_fulltextsearch/lib/Service/SearchService.php on line 217`

Indeed, if I delete lines 217, 218 and 219 the search is working but the result is not usable (i.e. I cannot click on the files to open them).

**Comment by daita** [comment]
please confirm that this issue can be closed

**Comment by Maurice-Mueller** [comment]
Sorry for the late reply. I just tested it and it works! Thanks!
