### ISSUE TITLE
Fulltextsearch brocken in nextcloud 15

### ISSUE THREAD

**Issue by prolibre** [nextcloud/files_fulltextsearch#28]
Nextcloud 15 in debian stretch (php 7.2)

Since my switch to nextcloud 15 (stable), fulltext search no longer works:
- fulltextsearch:live no longer detects file changes
- after reset fulltextsearch:index is broken > #22

**Comment by joe-speedboat** [comment]
Same problem for me, I do not find any other problem.
Thanks for helping out!
Installed on centos7 with ansible role: https://github.com/uniQconsulting-ag/ansible.nextcloud

BR
Chris


`[root@cloud ~]# occ status
  - installed: true
  - version: 15.0.0.10
  - versionstring: 15.0.0
  - edition: 
[root@cloud ~]# occ files_external:list
+----------+-------------+---------+---------------------+--------------------------+----------------------+------------------+-------------------+
| Mount ID | Mount Point | Storage | Authentication Type | Configuration            | Options              | Applicable Users | Applicable Groups |
+----------+-------------+---------+---------------------+--------------------------+----------------------+------------------+-------------------+
| 8        | /Data       | Local   | None                | datadir: "\/media\/data" | enable_sharing: true | chris            |                   |
+----------+-------------+---------+---------------------+--------------------------+----------------------+------------------+-------------------+
[root@cloud ~]# occ files_external:verify 8
  - status: ok
  - code: 0
  - message
[root@cloud ~]# occ app:list | egrep -i 'disabled|enabled|search'
Enabled:
  - files_fulltextsearch: 1.2.1
  - fulltextsearch: 1.2.1
  - fulltextsearch_elasticsearch: 1.2.1
Disabled:
[root@cloud ~]# curl -XGET http://localhost:9200/_cat/indices?v 
health status index     pri rep docs.count docs.deleted store.size pri.store.size 
yellow open   nextcloud   5   1          3            0     68.9kb         68.9kb 
[root@cloud ~]# occ fulltextsearch:stop
stopping all running indexes
[root@cloud ~]# occ fulltextsearch:check
Full text search 1.2.1
 
- Search Platform:
Elasticsearch 1.2.1
{
    "elastic_host": [
        "http:\/\/127.0.0.1:9200"
    ],
    "elastic_index": "nextcloud"
} 
 
- Content Providers:
Files 1.2.1
{
    "files_local": "1",
    "files_external": "0",
    "files_group_folders": "0",
    "files_encrypted": "0",
    "files_federated": "0",
    "files_size": "20",
    "files_pdf": "1",
    "files_office": "1",
    "files_image": "0",
    "files_audio": "0"
}
[root@cloud ~]# occ fulltextsearch:test
 
.Testing your current setup:  
Creating mocked content provider. ok  
Testing mocked provider: get indexable documents. (2 items) ok  
Loading search platform. (Elasticsearch) ok  
Testing search platform. ok  
Locking process ok  
Removing test. ok  
Pausing 3 seconds 1 2 3 ok  
Initializing index mapping. ok  
Indexing generated documents. ok  
Pausing 3 seconds 1 2 3 ok  
Retreiving content from a big index (license). (size: 32386) ok  
Comparing document with source. ok  
Searching basic keywords:  
 - 'test' (result: 1, expected: ["simple"]) ok  
 - 'document is a simple test' (result: 2, expected: ["simple","license"]) ok  
 - '"document is a test"' (result: 0, expected: []) ok  
 - '"document is a simple test"' (result: 1, expected: ["simple"]) ok  
 - 'document is a simple -test' (result: 1, expected: ["license"]) ok  
 - 'document is a simple +test' (result: 1, expected: ["simple"]) ok  
 - '-document is a simple test' (result: 0, expected: []) ok  
Updating documents access. ok  
Pausing 3 seconds 1 2 3 ok  
Searching with group access rights:  
 - 'license' - [] -  (result: 0, expected: []) ok  
 - 'license' - ["group_1"] -  (result: 1, expected: ["license"]) ok  
 - 'license' - ["group_1","group_2"] -  (result: 1, expected: ["license"]) ok  
 - 'license' - ["group_3","group_2"] -  (result: 1, expected: ["license"]) ok  
 - 'license' - ["group_3"] -  (result: 0, expected: []) ok  
Searching with share rights:  
 - 'license' - notuser -  (result: 0, expected: []) ok  
 - 'license' - user2 -  (result: 1, expected: ["license"]) ok  
 - 'license' - user3 -  (result: 1, expected: ["license"]) ok  
Removing test. ok  
Unlocking process ok  
 [root@cloud ~]#occ fulltextsearch:index

Options: []
Memory: 10 MB
┌─ Indexing  ────
│ Action: generateIndexFiles
│ Provider: Files                Account: admin
│ Document: 
│ Info: 
│ Title: 
│ Content size: 
│ Progress:      0/0
└──
┌─ Results ────
│ Result:      0/0
│ Index: 
│ Status: 
│ Message: 
│ 
│ 
└──
┌─ Errors ────
│ Error:      0/0
│ Index: 
│ Exception: 
│ Message: 
│ 
│ 
└──
## x:first result ## c/v:prec/next result ## b:last result
## f:first error ## h/j:prec/next error ## d:delete error ## l:last error
## q:quit ## p:pause 
An unhandled exception has been thrown:
TypeError: Argument 1 passed to OCA\Files_FullTextSearch\Model\MountPoint::setId() must be of the type integer, string given, called in /srv/nextcloud/html/apps/files_fulltextsearch/lib/Service/GroupFoldersService.php on line 220 and defined in /srv/nextcloud/html/apps/files_fulltextsearch/lib/Model/MountPoint.php:70
Stack trace:
#0 /srv/nextcloud/html/apps/files_fulltextsearch/lib/Service/GroupFoldersService.php(220): OCA\Files_FullTextSearch\Model\MountPoint->setId('1')
#1 /srv/nextcloud/html/apps/files_fulltextsearch/lib/Service/GroupFoldersService.php(123): OCA\Files_FullTextSearch\Service\GroupFoldersService->getMountPoints('admin')
#2 /srv/nextcloud/html/apps/files_fulltextsearch/lib/Service/FilesService.php(211): OCA\Files_FullTextSearch\Service\GroupFoldersService->initGroupSharesForUser('admin')
#3 /srv/nextcloud/html/apps/files_fulltextsearch/lib/Service/FilesService.php(181): OCA\Files_FullTextSearch\Service\FilesService->initFileSystems('admin')
#4 /srv/nextcloud/html/apps/files_fulltextsearch/lib/Provider/FilesProvider.php(228): OCA\Files_FullTextSearch\Service\FilesService->getFilesFromUser('admin', Object(OCA\FullTextSearch\Model\IndexOptions))
#5 /srv/nextcloud/html/apps/fulltextsearch/lib/Service/IndexService.php(179): OCA\Files_FullTextSearch\Provider\FilesProvider->generateIndexableDocuments('admin')
#6 /srv/nextcloud/html/apps/fulltextsearch/lib/Command/Index.php(407): OCA\FullTextSearch\Service\IndexService->indexProviderContentFromUser(Object(OCA\FullTextSearch_ElasticSearch\Platform\ElasticSearchPlatform), Object(OCA\Files_FullTextSearch\Provider\FilesProvider), 'admin', Object(OCA\FullTextSearch\Model\IndexOptions))
#7 /srv/nextcloud/html/apps/fulltextsearch/lib/Command/Index.php(271): OCA\FullTextSearch\Command\Index->indexProvider(Object(OCA\Files_FullTextSearch\Provider\FilesProvider), Object(OCA\FullTextSearch\Model\IndexOptions))
#8 /srv/nextcloud/html/3rdparty/symfony/console/Command/Command.php(255): OCA\FullTextSearch\Command\Index->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /srv/nextcloud/html/core/Command/Base.php(166): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /srv/nextcloud/html/3rdparty/symfony/console/Application.php(946): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /srv/nextcloud/html/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OCA\FullTextSearch\Command\Index), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /srv/nextcloud/html/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /srv/nextcloud/html/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /srv/nextcloud/html/console.php(96): OC\Console\Application->run()
#15 /srv/nextcloud/html/occ(11): require_once('/srv/nextcloud/...')
#16 {main}[root@cloud ~]# 
`

**Comment by daita** [comment]
I will release 1.2.2 today, but please create different report for different issues

**Comment by daita** [comment]
is this fixed ? can we close the issue ?

**Comment by pfaelzerchen** [comment]
For me it is fixed. Fulltextsearch is running fine now.

**Comment by prolibre** [comment]
For me it is fixed :-) thanks

**Comment by daita** [comment]
@joe-speedboat : please open a new issue with details on what is it trying to do when it crashes.

**Comment by joe-speedboat** [comment]
> ease open a new issue with details on what is it trying to do when it crashes.

@daita Sure, I will open new issue for that, thanks
