### ISSUE TITLE
New uploaded documents are not indexed

### ISSUE THREAD

**Issue by ettingerkarl** [nextcloud/files_fulltextsearch#30]
Under NC-15, no new data record is created in the table "fulltextsearch_indexes" when uploading a document. 
With NC-14, a new data record is created.

New installation of:
- NC-15
- Full text search 1.2.3
- Full text search - Elasticsearch Platform 1.2.2
- Full text search - Files 1.2.3

**Comment by daita** [comment]
are you using 15.0.2 ?

**Comment by p3pp0** [comment]
yes i am using 15.02
https://github.com/nextcloud/fulltextsearch/issues/434#issuecomment-457613318

**Comment by daita** [comment]
There was an issue with 15.0.0, but this was fixed in 15.0.2; is your file stored in a specific filesystem (not local) ?

**Comment by daita** [comment]
do you upload your file using the webclient, or directly on the external filesystem ?

**Comment by p3pp0** [comment]
directly on external filesystem

**Comment by dvaerum** [comment]
I have the same problem, but in addition the function index with also not "occ fulltextsearch:index" anything that I can search. Event through the process runs.

Versions
- NC-15
- Full text search 1.2.4
- Full text search - Elasticsearch Platform 1.2.3
- Full text search - Files 1.2.5

**Comment by acsfer** [comment]
Can you please confirm this still hapens with both latest versions of Nexcloud and `files_fulltextsearch` apps?

**Comment by joshtrichards** [comment]
Closing due to no further confirmations of reproducibility after 2+ years. Feel free to open a new issue or follow-up if this is actually still valid.
