### ISSUE TITLE
still not able to pass numeric user names...?

### ISSUE THREAD

**Issue by olli0815** [nextcloud/files_fulltextsearch#46]
An unhandled exception has been thrown:
TypeError: Argument 2 passed to OCA\Files_FullTextSearch\Service\FilesService::getPathFromViewerId() must be of the type string, integer given, called in /var/www/nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php on line 633 and defined in /var/www/nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php:399
Stack trace:

**Comment by daita** [comment]
Version used and trace ?

**Comment by olli0815** [comment]
FTS 1.2.4
FTS -EP 1.2.3
FTS -Files 1.2.5

#0 /var/www/nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php(633): OCA\Files_FullTextSearch\Service\FilesService->getPathFromViewerId(8, 123876)
#1 /var/www/nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php(571): OCA\Files_FullTextSearch\Service\FilesService->updateShareNames(Object(OCA\Files_FullTextSearch\Model\FilesDocument), Object(OC\Files\Node\Folder))
#2 /var/www/nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php(545): OCA\Files_FullTextSearch\Service\FilesService->updateDocumentAccess(Object(OCA\Files_FullTextSearch\Model\FilesDocument), Object(OC\Files\Node\Folder))
#3 /var/www/nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php(526): OCA\Files_FullTextSearch\Service\FilesService->updateFilesDocumentFromFile(Object(OCA\Files_FullTextSearch\Model\FilesDocument), Object(OC\Files\Node\Folder))
#4 /var/www/nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php(428): OCA\Files_FullTextSearch\Service\FilesService->updateFilesDocument(Object(OCA\Files_FullTextSearch\Model\FilesDocument))
#5 /var/www/nextcloud/apps/files_fulltextsearch/lib/Provider/FilesProvider.php(239): OCA\Files_FullTextSearch\Service\FilesService->generateDocument(Object(OCA\Files_FullTextSearch\Model\FilesDocument))
#6 /var/www/nextcloud/apps/fulltextsearch/lib/Service/IndexService.php(312): OCA\Files_FullTextSearch\Provider\FilesProvider->fillIndexDocument(Object(OCA\Files_FullTextSearch\Model\FilesDocument))
#7 /var/www/nextcloud/apps/fulltextsearch/lib/Service/IndexService.php(192): OCA\FullTextSearch\Service\IndexService->indexDocuments(Object(OCA\FullTextSearch_ElasticSearch\Platform\ElasticSearchPlatform), Object(OCA\Files_FullTextSearch\Provider\FilesProvider), Array, Object(OCA\FullTextSearch\Model\IndexOptions))
#8 /var/www/nextcloud/apps/fulltextsearch/lib/Command/Index.php(407): OCA\FullTextSearch\Service\IndexService->indexProviderContentFromUser(Object(OCA\FullTextSearch_ElasticSearch\Platform\ElasticSearchPlatform), Object(OCA\Files_FullTextSearch\Provider\FilesProvider), '123876', Object(OCA\FullTextSearch\Model\IndexOptions))
#9 /var/www/nextcloud/apps/fulltextsearch/lib/Command/Index.php(271): OCA\FullTextSearch\Command\Index->indexProvider(Object(OCA\Files_FullTextSearch\Provider\FilesProvider), Object(OCA\FullTextSearch\Model\IndexOptions))
#10 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\FullTextSearch\Command\Index->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/nextcloud/core/Command/Base.php(166): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/nextcloud/3rdparty/symfony/console/Application.php(946): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/nextcloud/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OCA\FullTextSearch\Command\Index), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/nextcloud/console.php(96): OC\Console\Application->run()
#17 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')

**Comment by daita** [comment]
please try last release
