### ISSUE TITLE
Update to 0.6.0 on NC 13 broken

### ISSUE THREAD

**Issue by linuxrrze** [nextcloud/files_fulltextsearch#5]
Hi,

I just updated to fulltextsearch apps to 0.6.0 on my nextcloud 13
installation. During upgrade of files_fulltextsearch the upgrade
process got stuck - nextcloud itself stopped working, all I get
is an error 500 from apache.

Apache log reports:

`PHP Fatal error:  Class OCA\\Files_FullTextSearch\\Provider\\FilesProvider contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCA\\FullTextSearch\\IFullTextSearchProvider::onRemovingIndex) in /proj.stand/cow/web/apps/nextcloud/instances/prod/nextcloud-13.0.0/apps/files_fulltextsearch/lib/Provider/FilesProvider.php on line 50
`

**Comment by JasperZ** [comment]
I had exactly the same problem with fulltextsearch. The Solution was to disable the app by command line and then the frontend was available again.

Disable app in command line(as apache user in nextcloud root folder):
`sudo -u apache php occ app:disable files_fulltextsearch`

**Comment by linuxrrze** [comment]
I did exactly the same thing, and nextcloud itself is working again.

However I'd really like to use the fulltextsearch feature - so I hope for a fix ;-)

**Comment by JasperZ** [comment]
For me it was possible to update the app in the ui "a second time" without any problems!?

**Comment by linuxrrze** [comment]
Hmm ... you're right ;-)
Thanks!
