### ISSUE TITLE
When enabled, richdocuments doesn't work anymore

### ISSUE THREAD

**Issue by ebogaard** [nextcloud/files_fulltextsearch#7]
Right after I enabled this app, richdocuments stopped working.
I wouldn't get to the online Collabora-editor anymore, but just get a regular download when I click on an openoffice file.

When I disable the app, I get the Collabora-editor again.

I was hoping to be able to have a full text index and online edit at the same time!

Enabled apps + version are:

Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - bruteforcesettings: 1.0.3
  - comments: 1.3.0
  - dav: 1.4.6
  - deck: 0.3.1
  - federatedfilesharing: 1.3.1
  - files: 1.8.0
  - files_automatedtagging: 1.3.0
  - files_external: 1.4.1
  - files_fulltextsearch: 0.6.0
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - fulltextsearch: 0.6.1
  - fulltextsearch_elasticsearch: 0.6.1
  - gallery: 18.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - richdocuments: 2.0.4
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - user_ldap: 1.3.1
  - user_saml: 1.4.2
  - workflowengine: 1.3.0

**Comment by daita** [comment]
Please try 0.8.0 and confirm this is fixed (or not)

**Comment by ebogaard** [comment]
Seems to be fixed!
We're going to test this some more, but so far it seems to be okay.

You can close this issue.
