### ISSUE TITLE
Github repo pwned?

### ISSUE THREAD

**Issue by Janhouse** [nextcloud/files_fulltextsearch#76]
It is very concerning to see "Hello from HackerOne" appear on repo Wiki. Are you pwned by some nice guys from HackerOne bounty program?

<img width="1271" alt="Screenshot 2019-08-05 at 5 16 23 PM" src="https://user-images.githubusercontent.com/1036439/62471205-da824200-b7a4-11e9-91b1-1b735cb689cc.png">

**Comment by Janhouse** [comment]
I guess you should contact @bilbomal who made the change.

**Comment by Janhouse** [comment]
Found the HackerOne page, https://hackerone.com/reports/457032
Why is the change in wiki not reverted?

**Comment by Lartza** [comment]
I've removed the little message left there, probably just an oversight when the report was handled. Wiki permissions should have been fixed as per the report, plese do report back if they aren't.
