### ISSUE TITLE
Null MIME type throws error in PHP 7.4.2

### ISSUE THREAD

**Issue by jernst** [nextcloud/files_fulltextsearch#91]
PHP has become pickier.

```
TypeError: Argument 1 passed to OCA\Files_FullTextSearch\Model\FilesDocument::setMimetype() must be of the type string, null given, called in .../apps/files_fulltextsearch/lib/Service/FilesService.php on line 409 and defined in ... /apps/files_fulltextsearch/lib/Model/FilesDocument.php:124
```

**Comment by jarvisaoieong** [comment]
I have same issue. 

When I run the `occ full:live` command and upload a word/pdf file from the web page, it will throw the `OCA\Files_FullTextSearch\Model\FilesDocument::setMimetype() must be of the type string, null given` error sometimes.

**Comment by daita** [comment]
should be fixed next release
