### ISSUE TITLE
NX18 - Could not resolve OCA\\OcSms\\Provider\\FullTextSearchProvider

### ISSUE THREAD

**Issue by hellkaim** [nextcloud/files_fulltextsearch#95]
So for unknown reason on NextCloud 18 (under revers proxy) full text search is not working.

I have FTS for Elasticsearch and FTS OCR extensions installed, but disabling or removing them does not help. I can see the search icon in the top navigation panel and even have a form for opening but that is it. Also the build-in search works grate as far as it goes.

The error is as follows:

`{"reqId":"N20lhDojKEgbc3IvDQMD","level":2,"time":"2020-07-18T23:50:51+00:00","remoteAddr":"10.10.10.10","user":"user","app":"fulltextsearch","method":"GET","url":"/apps/fulltextsearch/v1/search?request=%7B%22providers%22%3A%5B%22files%22%5D%2C%22options%22%3A%7B%22files_local%22%3A%221%22%2C%22files_external%22%3A%220%22%2C%22files_extension%22%3A%22%22%7D%2C%22search%22%3A%22new%22%2C%22page%22%3A1%7D","message":"Issue while loading Provider: ocsms/OCA\\OcSms\\Provider\\FullTextSearchProvider - OCP\\AppFramework\\QueryException Could not resolve OCA\\OcSms\\Provider\\FullTextSearchProvider! Class OCA\\OcSms\\Provider\\FullTextSearchProvider does not exist","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0","version":"18.0.7.1"}`

Please feel free to request any additional info needed.

**Comment by daita** [comment]
This issue is OcSms related
